{"uid":"5eff0808756cb522","name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","historyId":"c59643030e1e776644fd5d1d6aa79cfc","time":{"start":1676565813382,"stop":1676565813545,"duration":163},"status":"failed","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at new SemVer (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:23325:11)\n    at compare (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:23598:10)\n    at Function.gte (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:23647:10)\n    at Object.eval (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:24251:12)\n    at Object../node_modules/utf7/utf7.js (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:24368:30)\n    at __webpack_require__ (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:20:30)\n    at Object.eval (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:17525:12)\n    at Object../node_modules/imap/lib/Connection.js (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:19648:30)\n    at __webpack_require__ (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:20:30)\n    at Object.eval (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:14357:12)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":9,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at new SemVer (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:23325:11)\n    at compare (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:23598:10)\n    at Function.gte (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:23647:10)\n    at Object.eval (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:24251:12)\n    at Object../node_modules/utf7/utf7.js (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:24368:30)\n    at __webpack_require__ (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:20:30)\n    at Object.eval (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:17525:12)\n    at Object../node_modules/imap/lib/Connection.js (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:19648:30)\n    at __webpack_require__ (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:20:30)\n    at Object.eval (http://localhost:35991/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:14357:12)","steps":[],"attachments":[{"uid":"e248cb93e2ea5141","name":"1-createIndividualAccount-spec10.js:2023-02-16T16:43:33.422Z","source":"e248cb93e2ea5141.png","type":"image/png","size":50744}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"e10389e3c5e1b441","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676565802574,"stop":1676565802741,"duration":167}},{"uid":"3e1c72a800d994cc","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676565791570,"stop":1676565791755,"duration":185}},{"uid":"71547ad55cda545e","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676565780672,"stop":1676565780839,"duration":167}},{"uid":"d3cca75bc894f181","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676565769804,"stop":1676565769971,"duration":167}},{"uid":"3be8899c83ec93e6","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676565759122,"stop":1676565759289,"duration":167}},{"uid":"d8a375d8a2d5c4ee","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676565748359,"stop":1676565748523,"duration":164}},{"uid":"cffa4ce3baa2b07b","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676565737686,"stop":1676565737856,"duration":170}},{"uid":"74a0629f7bf08e7f","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676565726972,"stop":1676565727142,"duration":170}},{"uid":"8a22745ab670738c","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676565714029,"stop":1676565714188,"duration":159}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":2,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"33292fb500ca1eb3","reportUrl":"https://qa-github1.github.io/nucleus3/38//#testresult/33292fb500ca1eb3","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676564388294,"stop":1676564388456,"duration":162}}]},"tags":[]},"source":"5eff0808756cb522.json","parameterValues":[]}